### ISSUE TITLE
RX Broadcast breaks Etherbone communication

### ISSUE THREAD

**Issue by duqiang** [enjoy-digital/liteeth#107]
I found the https://github.com/enjoy-digital/liteeth/commit/aff1916a039815861f428270e48fe0e4175cc785 breaks my Etherbone communication, where I do not wish the board to receive broadcast packets anyway.

Is it feasible to set the default value of `with_broadcast` to `False` at https://github.com/enjoy-digital/liteeth/blob/master/liteeth/core/ip.py#L259, or to expose the parameter?

It seems this issue is related with https://github.com/enjoy-digital/liteeth/issues/101:
> RX Broadcast is now enabled by default with https://github.com/enjoy-digital/liteeth/commit/aff1916a039815861f428270e48fe0e4175cc785. A parameter has been added to enabled/disable it and should ease code comprehension.

> TX Broadcast is now also possible with https://github.com/enjoy-digital/liteeth/commit/dc96269c8ffce46b6ed61ac85a3c6bdc74946692.

> _Originally posted by @enjoy-digital in https://github.com/enjoy-digital/liteeth/issues/101#issuecomment-1041484136_

**Comment by enjoy-digital** [comment]
Thanks, this is exposed with https://github.com/enjoy-digital/liteeth/commit/a31958884346fe0218a451103f28b60ea74144c6 and https://github.com/enjoy-digital/litex/commit/c4e3962deff5ad2d7f4c1ad8c76117b503632279.
