### ISSUE TITLE
Ethernet connection via switch

### ISSUE THREAD

**Issue by lapnd** [enjoy-digital/liteeth#108]
Hi,
I'm using DE2-115 board using MII mode. The netboot works fine (LiteX can download bios/linux image from TFTP server) if the board connects to the PC directly. If the board connect to the PC via switch, the netboot doesn't work any more. Is that because LiteEth doesn't support connection via switch?

**Comment by romanetz** [comment]
Hi @lapnd ! Please check whether connection speed is 1000 or 100 megabits over switch and directly. In my case that was the reason. The liteeth in my setup didn't work at 100 megabits but perfectly with gigabit speed . RGMII PHY specifications state that according to the link speed, eth_tx_clk and eth_rx_clk must be in accordance :125 MHz when link speed is 1000, 25 MHz when link speed is 100 and only 2.5 MHz when link speed is 10 megabits.
