### ISSUE TITLE
example_designs: invalid path

### ISSUE THREAD

**Issue by blshkv** [enjoy-digital/liteeth#14]
```
 * Detected file collision(s):
 * 
 *      /usr/lib64/python3.6/site-packages/example_designs/make.py
 *      /usr/lib64/python3.6/site-packages/example_designs/__init__.py
 *      /usr/lib64/python3.6/site-packages/example_designs/targets/__init__.py
 *      /usr/lib64/python3.5/site-packages/example_designs/make.py
 *      /usr/lib64/python3.5/site-packages/example_designs/__init__.py
 *      /usr/lib64/python3.5/site-packages/example_designs/targets/__init__.py
```

both litepcie and liteeth (and may be other lite*) install this directory into the same location from setup.py

**Comment by enjoy-digital** [comment]
example_designs are not supposed to be installed. Can you try removing the __init__.py file from example designs and retry the installation?

**Comment by blshkv** [comment]
Please go ahead and delete ```__init__.py```. It fixed the issue.
Thank you

**Comment by enjoy-digital** [comment]
This should be solved by https://github.com/enjoy-digital/liteeth/commit/6b872fd2711905a18f15733466f711f021765dd5.

**Comment by blshkv** [comment]
not fixed properly:
```
 * ERROR: sci-electronics/liteeth-20180718::pentoo failed (install phase):
 *   Package installs 'test' package which is forbidden and likely a bug in the build system.

```

**Comment by blshkv** [comment]
you also failed to patch all other lite* packages

**Comment by enjoy-digital** [comment]
ok thanks, will have another look at that.

**Comment by enjoy-digital** [comment]
it should be good now, can you test? If that's not good, can you suggest a patch since i'm not able to reproduce the issue? (i'd like to keep the `__init__.py` since that's useful for others things).

**Comment by blshkv** [comment]
ok, it works now. Thanks!
https://github.com/enjoy-digital/liteeth/commit/24b0d2b8c2cfcf96a8c6cb56ec01af9a56952aad
