### ISSUE TITLE
IP header contains null destination address

### ISSUE THREAD

**Issue by jrsa** [enjoy-digital/liteeth#147]
I instantiated this core in a very simple litex soc design with `add_etherbone` and it seems to work, except that packets sent from the core do not have the destination MAC address set to the one given by the ARP reply, it is set to all zeros. `tcpdump` on the computer can see these packets, but software such as `litex_server` will not. As a workaround, I hardcoded my computer's MAC address [here](https://github.com/enjoy-digital/liteeth/blob/master/liteeth/core/ip.py#L173) and then `litex_server` and `litex_cli` work as expected, except that I would have to resynthesize the design if I needed to switch computers :)

I am fairly new to litex and HDL in general, and thus have not yet tried to debug this myself. I have not discounted the possibility that something is incorrectly configured on my computer that would break ARP but it doesn't seem very likely. For what it's worth, I am able to use ethernet via software, using `--with-ethernet` rather than `--with-etherbone` to build the SoC and booting the prebuilt linux image from [here](https://github.com/litex-hub/linux-on-litex-vexriscv/issues/164) with the same host computer.

The target board is LambdaConcept ECPIX-5 which is supported by litex-boards. The command I used to build is
```
python -m litex_boards.targets.lambdaconcept_ecpix5 --with-etherbone --build --load --flash
```

I do not have anything hooked up to the board except a USB cable for the FT2232 interface and an ethernet cable.

tcpdump showing one etherbone packet in each direction, with the reply containing `00:00:00:00:00:00` as the destination address:
```
20:56:14.227301 18:c0:4d:31:67:5c > 10:e2:d5:00:00:00, ethertype IPv4 (0x0800), length 54: (tos 0x0, ttl 64, id 17444, offset 0, flags [DF], proto UDP (17), length 40)
    192.168.1.100.1234 > 192.168.1.50.1234: [bad udp cksum 0x840c -> 0x1288!] UDP, length 12
20:56:14.227350 10:e2:d5:00:00:00 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.1.100 (ff:ff:ff:ff:ff:ff) tell 192.168.1.50, length 46
20:56:14.227353 18:c0:4d:31:67:5c > 10:e2:d5:00:00:00, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Reply 192.168.1.100 is-at 18:c0:4d:31:67:5c, length 28
20:56:14.227433 10:e2:d5:00:00:00 > 00:00:00:00:00:00, ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 40)
    192.168.1.50.1234 > 192.168.1.100.1234: [no cksum] UDP, length 12
```

**Comment by rowanG077** [comment]
that's definitely not expected. There recently were some ARP changes. Can you try to use commit df053ae7399a2fc020f72ed7c687f4448497bfe7? If that works that's a clear indication a bug was introduced.

**Comment by jrsa** [comment]
@rowanG077 it is working after reverting to that commit

**Comment by AndrewD** [comment]
I can confirm that I'm see the same bahaviour. A simple test case is to build targets/digilent_arty with etherbone.

Pinging etherbone gives the behaviour described above. This seems to be platform specific because it works with ti60_f225.

@enjoy-digital which hardware were you testing with for the arp changes?

**Comment by enjoy-digital** [comment]
Thanks all for the feedback, I'll do more tests and will fix it.

**Comment by enjoy-digital** [comment]
Exact breaking commit is https://github.com/enjoy-digital/liteeth/commit/c5b53326bb3fc3e9f89f451e9d9663b7a6449dcc.
