### ISSUE TITLE
libuip configuration files assumes CPU endianness

### ISSUE THREAD

**Issue by jeanthom** [enjoy-digital/liteeth#18]
In `contiki-conf.h` the CPU endianness is defined to *big*. This causes issues on little endian CPUs like the PicoRV32.

https://github.com/enjoy-digital/liteeth/blob/2424e62bf9637c2623b627a56aca7a3f90349e92/liteeth/software/libuip/contiki-conf.h#L30

I think we could add a macro in the generated header `csr.h` to indicate this, and then add a ternary operator in `contiki-conf.h`.

**Comment by enjoy-digital** [comment]
I removed the libuip example code. Example of LiteETH integrated with libuip can be found in https://github.com/timvideos/HDMI2USB-litex-firmware/tree/master/firmware.
