### ISSUE TITLE
IPv4 total length exceeds packet length (50 bytes)

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/liteeth#25]
I noticed the following error;

![image](https://user-images.githubusercontent.com/21212/72489600-3bd43400-3860-11ea-9dcf-035c5176c5d8.png)

**Comment by mithro** [comment]
![image](https://user-images.githubusercontent.com/21212/72491689-7e990a80-3866-11ea-899f-e7f0823f86bc.png)

**Comment by jersey99** [comment]
@mithro Could you give a little more information of your setup? Has this worked for you in the past on the same device?

**Comment by mithro** [comment]
This is on the arty board with https://github.com/mithro/litex-buildenv/blob/etherbone/targets/arty/etherbone.py

It uses the LiteEth UDP core.

Using the software version of LiteEth and libuip the board works fine.

**Comment by enjoy-digital** [comment]
@mithro: it seems there is a regression on Packetizer/Depacketizer from https://github.com/enjoy-digital/litex/blob/master/litex/soc/interconnect/packet.py. I got https://github.com/enjoy-digital/litex/commit/a168ecbabd47a6378b6d5ef560b464900d07c863 working by reverting packet.py to [packet.py.txt](https://github.com/enjoy-digital/liteeth/files/4070006/packet.py.txt). I'm bisecting things now. (strangely, there are no regression on 1Gbps Etherbone or with litex_sim).

**Comment by enjoy-digital** [comment]
It should be fixed with https://github.com/enjoy-digital/litex/commit/a26853702c109fb4e650ef2d53cfd631a4bec328, @mithro can you try?

**Comment by mithro** [comment]
Seems to be fixed!
