### ISSUE TITLE
EtherBone data conversion issue

### ISSUE THREAD

**Issue by jedrzejboczar** [enjoy-digital/liteeth#52]
While investigating https://github.com/antmicro/litex-rowhammer-tester/issues/7 I noticed that even in simulation there are problems with data read from memory over EtherBone.

The issue is that when reading following words with expected result of e.g. `11 22 33 44 55 66 77 88` I get `11 22 33 44 55 66 77 44`. After some debugging I noticed problem in the [tx converter in udp crossbar](https://github.com/enjoy-digital/liteeth/blob/master/liteeth/core/udp.py#L55):
![tx_converter_sim](https://user-images.githubusercontent.com/16623787/97898352-0b4e7f80-1d38-11eb-92f3-70db761ff9d4.png)

It seems that `sink_valid` is held high all the time, but the data is not being changed fast enough on `sink_ready`. The port writing to the `user_port` [is driven by the tx packetizer](https://github.com/enjoy-digital/liteeth/blob/master/liteeth/frontend/etherbone.py#L149).

`LiteEthEtherbonePacketTX`'s FSM is in `SEND` state all the time, `LiteEthEtherbonePacketPacketizer`'s FSM is in `ALIGNED-DATA-COPY`, so the issue must be on/before `LiteEthEtherbonePacket` sink. I will yet investigate more, but maybe you have some suggestions.

**Comment by enjoy-digital** [comment]
Thanks @jedrzejboczar for the investigation. `sink_data` is indeed updated 1 cycle too late. Would you mind sharing a capture with the signals of the **packetizer** (at least sink/source of LiteEthEtherbonePacketPacketizer)? Otherwise if you have a minimal repro i can also have a closer look.

**Comment by jedrzejboczar** [comment]
I checked the stream further down the path and the packetizer is ok. It goes through `Arbiter` to `LiteEthEtherboneRecord` then `LiteEthEtherboneRecordSender`: 
![etherbone](https://user-images.githubusercontent.com/16623787/97971650-a9d3f280-1dc3-11eb-8fab-7ce22dae52d4.png)

It seems that the problem arises from this assignment being synchronious:
https://github.com/enjoy-digital/liteeth/blob/c9334d6b3eb2060c151f1d68b2880d8bcea3c831/liteeth/frontend/etherbone.py#L314
as the data on `fifo_source` is correct but `sender_source` is too late.

**Comment by jedrzejboczar** [comment]
After changing that block to `comb` it seems I am getting correct data, but I am not sure if this is entirely correct, as the `11223344` word is set on `tx_converter_sink` at previous `ready` as visible here:
![etherbone2](https://user-images.githubusercontent.com/16623787/97973738-d3424d80-1dc6-11eb-95db-ae511909b800.png)

**Comment by jedrzejboczar** [comment]
Ah, ok, that was due to this:
https://github.com/enjoy-digital/liteeth/blob/c9334d6b3eb2060c151f1d68b2880d8bcea3c831/liteeth/frontend/etherbone.py#L323-L324
Removing line 324 fixes the problem with new data being visible during old `ready`. Do you think it should all be `comb`? Or better use `sync` and delay the `valid` signal by 1 cycle (something like changing line 321 to `source.valid.eq(~source.ready)`?

**Comment by enjoy-digital** [comment]
OK good. I'll look at this to see if there was a specific reason to use `sync`, if not, we should probably indeed simplify the code to only use `comb` (and eventually add a Buffer on the `sink` or `source `if it degrades timings).
