### ISSUE TITLE
Semicolon?

### ISSUE THREAD

**Issue by davidcorrigan714** [enjoy-digital/liteeth#58]
Guessing no one's intentionally hit [this else condition](https://github.com/enjoy-digital/liteeth/blob/7448170390ddf4b7c353ae10932377255581c25a/liteeth/gen.py#L203) yet, don't think it'll appreciate the semicolon though I think it ends up being an exception regardless.

**Comment by enjoy-digital** [comment]
Thanks @davidcorrigan714, this has been removed with https://github.com/enjoy-digital/liteeth/commit/9edf5d393f68a3561472c5ce2130c8ee409aedb8.
