### ISSUE TITLE
Add support for Etherbone broadcast

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/liteeth#7]
Etherbone supports discovery via broadcast. This should be as simple as responding to Etherbone messages on the broadcast IP address (but responding as if it was sent to your actual IP address?).

Will update with more details once I understand how it works better (and probably send a pull request - Feel free to assign to me.)

**Comment by enjoy-digital** [comment]
This is now supported by https://github.com/enjoy-digital/litex/commit/b02753ecfae9f6be9ff8dafe7d28c68ef7d3aa30 that adds UDP scan capability to LiteX Server. This has also been documented in https://github.com/enjoy-digital/litex/wiki/Use-Host-Bridge-to-control-debug-a-SoC.
