### ISSUE TITLE
Import "soft" etherbone support into LiteEth

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/liteeth#8]
In the HDMI2USB-litex-firmeware, @enjoy-digital added "soft" etherbone support. IE Etherbone support done in software under libuip. See  https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/firmware/etherbone.h and https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/firmware/etherbone.h

This is probably useful for anyone using libuip so should probably live in LiteEth.

A lot of the source could also be useful for other soft implementations such as running on the computer, running in qemu, or other IP stacks too.

(Feel free to assign to me.)

**Comment by enjoy-digital** [comment]
With the recent Zephyr, NuttX, Linux ports, i would rather spend time improving full OSes support than libuip. If useful, the code can still be found in https://github.com/timvideos/HDMI2USB-litex-firmware/tree/master/firmware.
