### ISSUE TITLE
Support etherbone hardware core on Opsis / Atlys boards?

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/liteeth#9]
The Etherbone support in LiteEth / LiteX currently doesn't have a good example of how to use it on Spartan 6 FPGAs (such as the Opsis / Atlys boards).

From @enjoy-digital ;
> The gateware version requires a soc with freq > 125MHz
> I removed this limitation for a project, but you still have to run the ethernet part at a freq > 125MHz

@enjoy-digital suggested something like the following might work but it needs to be tested;
```python
            ethphy = LiteEthPHYGMII(self.platform.request("eth_clocks"), self.platform.request("eth"))
            ethphy = ClockDomainsRenamer("eth")(ethphy)
            ethcore = LiteEthUDPIPCore(ethphy,
                mac_address=0x10e2d5000000,
                ip_address=convert_ip("192.168.1.50"),
                clk_freq=eth_clk_freq,
                with_icmp=True)
            ethcore = ClockDomainsRenamer("eth")(ethcore)
            self.submodules += ethphy, ethcore
            # etherbone bridge
            etherbone_cd = ClockDomain("etherbone") # similar to sys but need for correct
            self.clock_domains += etherbone_cd # clock domain renaming
            self.comb += [
                etherbone_cd.clk.eq(ClockSignal("sys")),
                etherbone_cd.rst.eq(ResetSignal("sys"))
            ]
            self.submodules.etherbone = LiteEthEtherbone(ethcore.udp, 1234, cd="etherbone")
            self.add_wb_master(self.etherbone.wishbone.bus)
```

See https://github.com/mithro/HDMI2USB-litex-firmware/blob/litescope/targets/opsis/scope_net.py for my initial attempt before finding about the above problem.

**Comment by enjoy-digital** [comment]
The suggested code has been tested on various boards. This issue should probably be integrated in litex-buildenv is still actual.
